### ISSUE TITLE
Persisting Xtext DSL using neoEMF

### ISSUE THREAD

**Issue by aianta** [atlanmod/NeoEMF#101]
I'm trying to persist the EMF model for a DSL I am working on, however whenever I try to copy an EObject over from an XtextResource to a PersistentResource I am getting the following error:

 `java.lang.NoSuchMethodError: org.worklang.work.impl.ModelImpl.resource(Lorg/eclipse/emf/ecore/resource/Resource$Internal;)V
        at org.worklang.work.impl.ModelImpl$$EnhancerByCGLIB$$cd11840f.CGLIB$resource$130(<generated>)
        at org.worklang.work.impl.ModelImpl$$EnhancerByCGLIB$$cd11840f$$FastClassByCGLIB$$7780dc06.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at fr.inria.atlanmod.neoemf.core.PersistentEObjectAdapter$PersistentEObjectProxyHandler.intercept(PersistentEObjectAdapter.java:152)
        at org.worklang.work.impl.ModelImpl$$EnhancerByCGLIB$$cd11840f.resource(<generated>)
        at fr.inria.atlanmod.neoemf.resource.DefaultPersistentResource$ResourceContentsEStoreEList.delegateAdd(DefaultPersistentResource.java:454)
        at org.eclipse.emf.ecore.impl.EStoreEObjectImpl$BasicEStoreEList.delegateAdd(EStoreEObjectImpl.java:194)
        at org.eclipse.emf.common.util.DelegatingEList.addUnique(DelegatingEList.java:308)
        at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.doAddUnique(DelegatingNotifyingListImpl.java:317)
        at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.addUnique(DelegatingNotifyingListImpl.java:301)
        at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:303)
        at org.worklang.generator.WorkGenerator.lambda$doGenerate$0(WorkGenerator.java:50)
        at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:426)
        at org.worklang.generator.WorkGenerator.doGenerate(WorkGenerator.java:53)
        at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:43)
        at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:34)`

The EObject copy code looks like this, it's written in my DSL's Xtend Code Generator:

		PersistenceBackendFactoryRegistry.register(BlueprintsURI.SCHEME,BlueprintsPersistenceBackendFactory.getInstance())
		
		var ResourceSet dbResourceSet = new ResourceSetImpl();
		dbResourceSet.resourceFactoryRegistry.protocolToFactoryMap.put(BlueprintsURI.SCHEME, PersistentResourceFactory.getInstance())
		
		val PersistentResource dbResource = dbResourceSet.createResource(BlueprintsURI.createFileURI(new File("workgraph.work"))) as PersistentResource
		
		var Map<String, Object> options = BlueprintsOptionsBuilder.newBuilder.autocommit.asMap
		
		dbResource.save(options)
		
		//Copy all work file contents into db resource
		
		val Copier copier = new Copier

		
		resource.allContents
			.forEach[ele|
				
				dbResource.contents.add(copier.copy(ele))
				
				println(copyOfEle.eClass.instanceTypeName)

			]
			
		//Persist db resource
		dbResource.save(options)

I have no doubt that I am approaching this the wrong way, there seems to be a fundamental difference between the XtextResource and DefaultPersistentResource used by neoEMF. But I'm new to EMF, Xtext, and neoEMF, and would appreciate any pointers you could offer.

**Comment by gdaniel** [comment]
Hi aianta,

This error looks like a code generation error. Do you generate the code from the ecore metamodel representing your grammar? If so, check that you use a NeoEMF genmodel (New -> EMF Generator Model -> *NeoEMF Native Importer*)

This CGLIB-related issue is typically thrown when you manipulate Dynamic EObjects (non-generated code) or when you use standard EObjects (generated code from the standard Ecore importer). You can find some information about this issue on the [wiki](https://github.com/atlanmod/NeoEMF/wiki/FAQ#i-get-an-unsupportedoperationexception-when-i-save-a-model).

If you manage to generate NeoEMF-specific code you'll probably have to tell XText to use it instead of dynamic EObjects. If I remember well you can create a new XText project from an existing metamodel.

Cheers,

Gwendal

**Comment by aianta** [comment]
Thank you, I'll look into generating NeoEMF specific code and hooking up Xtext from there.  I've also done some more reading on EMF and things seem a lot more clear.
