### ISSUE TITLE
DirectStoreList.contains is unsafe to use

### ISSUE THREAD

**Issue by paulreuter** [atlanmod/NeoEMF#102]
Calling contains on a NeoEMF store-backed list (FeatureMap as well) throws an UnsupportedOperationException if the object in question is not a PersistentEObject.

This breaks most Commands employed by EMF generated tree editors, among other things.

**Comment by sunye** [comment]
Dear Paul,

This is not an issue, NeoEMF can only work with `PersistentObject` implementations, i.e., instances of classes that were generated with a NeoEMF  `.genmodel` file.

For persisting EMF objects, an extra behaviour is needed. That's why classes generated from EMF's default `.genmodel` files are not supported.

Best regards,

**Comment by paulreuter** [comment]
Dear Gerson,

thank you for your answer, but I respectfully disagree that this is not an issue. Even without any intention to mix NeoEMF and classic EMF objects, the UI code of the Eclipse framework may cause trouble. 

When I open an (EMF generated) editor on the NeoEMF content tree and select something, the commands in the context menu will update and evaluate their enablement status.

If there are other, non-NeoEMF models loaded, the CreateChildCommand may cause trouble for NeoEMF elements containing wildcard features.

If a non-NeoEMF object is in the copy & paste buffer, the PasteCommand may interact with NeoEMF objects unfavourably.

Even without foreign models, there may be problems. In the following stacktrace I selected a leaf node that is a String entry in a feature map (in NeoEMF). 

```
java.lang.IllegalArgumentException: Unable to create a PersistentEObject adapter for this object of type SimpleFeatureMapEntry
	at fr.inria.atlanmod.commons.Preconditions.checkArgument(Preconditions.java:97)
	at fr.inria.atlanmod.neoemf.core.PersistenceAdapter.adapt(PersistenceAdapter.java:101)
	at fr.inria.atlanmod.neoemf.core.PersistenceAdapter.adapt(PersistenceAdapter.java:121)
	at fr.inria.atlanmod.neoemf.core.PersistentEObject.from(PersistentEObject.java:42)
	at fr.inria.atlanmod.neoemf.data.store.adapter.AbstractStoreAdapter.contains(AbstractStoreAdapter.java:380)
	at fr.inria.atlanmod.neoemf.core.internal.DirectStoreList.delegateContains(DirectStoreList.java:93)
	at org.eclipse.emf.common.util.DelegatingEList.contains(DelegatingEList.java:97)
	at org.eclipse.emf.ecore.util.DelegatingEcoreEList.contains(DelegatingEcoreEList.java:489)
	at org.eclipse.emf.edit.provider.ItemProviderAdapter.factorRemoveCommand(ItemProviderAdapter.java:1349)
	at org.eclipse.emf.edit.provider.ItemProviderAdapter.createCommand(ItemProviderAdapter.java:1015)
	at org.eclipse.emf.edit.domain.AdapterFactoryEditingDomain.createCommand(AdapterFactoryEditingDomain.java:462)
	at org.eclipse.emf.edit.domain.AdapterFactoryEditingDomain.createCommand(AdapterFactoryEditingDomain.java:516)
	at org.eclipse.emf.edit.command.RemoveCommand.create(RemoveCommand.java:93)
	at org.eclipse.emf.edit.command.RemoveCommand.create(RemoveCommand.java:85)
	at org.eclipse.emf.edit.command.DeleteCommand.prepareCommand(DeleteCommand.java:104)
	at org.eclipse.emf.edit.command.DeleteCommand.prepare(DeleteCommand.java:98)
	at org.eclipse.emf.common.command.AbstractCommand.canExecute(AbstractCommand.java:108)
	at org.eclipse.emf.edit.ui.action.CommandActionHandler.updateSelection(CommandActionHandler.java:99)
	at org.eclipse.ui.actions.BaseSelectionListenerAction.selectionChanged(BaseSelectionListenerAction.java:124)
```
As you can see, the entire relevant stacktrace from the selection change event is framework code, and very little I can do to prevent this issue.

Kind regards,
