### ISSUE TITLE
NPE when adding new objects to previously saved models

### ISSUE THREAD

**Issue by buchgeher** [atlanmod/NeoEMF#6]
Hi,

I'm still trying to integrate NeoEMF as persistence backend in our project. So far I can create and save and load a new model. However, when I am adding a new element to the previously saved and after program restart new loaded model I am getting an NPE - see the stacktrace below. Removing elements and modifying existing elements work without problems. 

Stack Trace:
!ENTRY org.eclipse.emf.common 2 0 2015-10-07 14:06:28.366
!MESSAGE An exception was ignored during command execution
!STACK 0
org.eclipse.emf.common.util.WrappedException: An exception was ignored during command execution
	at org.eclipse.emf.common.command.BasicCommandStack.handleError(BasicCommandStack.java:281)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.handleError(AbstractTransactionalCommandStack.java:125)
	at org.eclipse.emf.common.command.BasicCommandStack.execute(BasicCommandStack.java:112)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.basicExecute(AbstractTransactionalCommandStack.java:241)
	at org.eclipse.emf.transaction.impl.TransactionalCommandStackImpl.doExecute(TransactionalCommandStackImpl.java:63)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:219)
	at org.lisa.air.server.infrastructure.internal.executor.Executor.executeOperation(Executor.java:157)
	at org.lisa.air.server.infrastructure.internal.InfrastructureManagement.createModule(InfrastructureManagement.java:87)
	at org.lisa.air.client.infrastructure.internal.handler.CreateModuleHandler.executeOperation(CreateModuleHandler.java:29)
	at org.lisa.air.client.infrastructure.handler.ModelOperationHandler.execute(ModelOperationHandler.java:14)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:825)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:701)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$6(HandledContributionItem.java:685)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:613)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.NullPointerException
	at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackend.getOrCreateVertex(BlueprintsPersistenceBackend.java:172)
	at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.estores.impl.DirectWriteBlueprintsResourceEStoreImpl.add(DirectWriteBlueprintsResourceEStoreImpl.java:370)
	at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.estores.impl.DirectWriteBlueprintsResourceEStoreImpl.add(DirectWriteBlueprintsResourceEStoreImpl.java:346)
	at org.eclipse.emf.ecore.impl.EStoreEObjectImpl$BasicEStoreEList.delegateAdd(EStoreEObjectImpl.java:188)
	at org.eclipse.emf.common.util.DelegatingEList.addUnique(DelegatingEList.java:334)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.doAddUnique(DelegatingNotifyingListImpl.java:379)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.addUnique(DelegatingNotifyingListImpl.java:275)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:303)
	at org.lisa.air.server.infrastructure.internal.model.operations.CreateModuleOperation.execute(CreateModuleOperation.java:35)
	at org.lisa.air.server.infrastructure.internal.executor.Executor$1.execute(Executor.java:99)
	at org.eclipse.emf.common.command.BasicCommandStack.execute(BasicCommandStack.java:78)
	... 53 more

!ENTRY org.eclipse.emf.common 2 0 2015-10-07 14:06:28.367
!MESSAGE An exception was ignored during command execution
!STACK 0
org.eclipse.emf.common.util.WrappedException: An exception was ignored during command execution
	at org.eclipse.emf.common.command.BasicCommandStack.handleError(BasicCommandStack.java:281)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.handleError(AbstractTransactionalCommandStack.java:125)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:229)
	at org.lisa.air.server.infrastructure.internal.executor.Executor.executeOperation(Executor.java:157)
	at org.lisa.air.server.infrastructure.internal.InfrastructureManagement.createModule(InfrastructureManagement.java:87)
	at org.lisa.air.client.infrastructure.internal.handler.CreateModuleHandler.executeOperation(CreateModuleHandler.java:29)
	at org.lisa.air.client.infrastructure.handler.ModelOperationHandler.execute(ModelOperationHandler.java:14)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:825)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:701)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$6(HandledContributionItem.java:685)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:613)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: org.eclipse.emf.transaction.RollbackException: 
	at org.eclipse.emf.transaction.impl.TransactionImpl.commit(TransactionImpl.java:405)
	at org.eclipse.emf.transaction.impl.TransactionalCommandStackImpl.doExecute(TransactionalCommandStackImpl.java:70)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:219)
	... 49 more

**Comment by gdaniel** [comment]
Hi,

What is the list you are trying to add elements to? (the call from CreateModuleOperation.java:35).
Does eClass() method returns something for the element you are adding?

**Comment by buchgeher** [comment]
The list I'm trying to add my element is an EStoreEObjectImpl$BasicEStoreEList. 
The eClass() method for the element I'm trying to add returns me an EClassImpl Object.

![capture](https://cloud.githubusercontent.com/assets/10845116/10359902/ec7ba948-6d9c-11e5-86d8-37b73cac9e37.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10845116/10359907/f4fbf564-6d9c-11e5-8b9f-d79eb3da1052.PNG)

**Comment by buchgeher** [comment]
I have created a sample plug-in to reproduce the error. 
Steps to reproduce
- start application, make sure that plug-in has started
- shutdown the application (just stopping the plug-in is not enough)
- restart the application

The plug-in can be found here: https://dl.dropboxusercontent.com/u/366920/issueexample.zip

**Comment by gdaniel** [comment]
Hi,
I have found the problem, I'll publish a fix soon

**Comment by gdaniel** [comment]
I have put a new update site with the correction.
The problem was related to graph copy which does not take into account existing indexes.
Some errors in TinkerGraph serialization / loading are also fixed.

One point about using default blueprints backend: the default graph implemetation is TinkerGraph, which is an in-memory graph. Even if it is serialized and persisted when the resource is saved, it is more or less like XMI: the file containing the graph has to be loaded completely in memory to become usable. If you give a try to NeoEMF due to scalability issues, I suggest you should use MapDB or Neo4j implementation.
(Here)[https://hal.inria.fr/hal-01140776/document] is an article that explains Map data model and compares it to Graph one (Neo4j). Even if some updates have been done on the project, this comparison can be a good starting point.

You can see how to instantiate a Neo4j backend in the (Usage.md)[https://github.com/atlanmod/NeoEMF/blob/master/Usage.md#neo4j-blueprints-complete-example-modify-an-existing-resource] file.

Regards,

Gwendal

**Comment by buchgeher** [comment]
I using the sample code from the Usage.md file 1:1 (the one for neo4j), but obviously my model gets saved using the TinkerGraph default implementation. Is there anything else I need to consider when using the neo4j backend?

**Comment by gdaniel** [comment]
Your TinkerGraph persisted model cannot be loaded again for 2 reasons:
* The indexes built during the insertion have been lost (that's what I solved in the last commit)
* We changed the TinkerGraph serialization because it caused loading errors (see [here](https://github.com/tinkerpop/blueprints/issues/285) and [here](https://github.com/tinkerpop/rexster/issues/299))

You will need to re-create your model using the Neo4j graph type option (see [ResourceConfiguration wiki page](https://github.com/atlanmod/NeoEMF/wiki/Resource-Configuration)).
If the size of your model is important and the operation takes time, you may be interested in the different resource options available to customize the Neo4j implementation.

**Comment by buchgeher** [comment]
I tried to enable the Neo4J Backend as described in the Resource Configuration page. However, when I start my application I am getting some class not found exceptions (see below). I started with a completely new model. 

13:12:57.513 [pool-1-thread-1] WARN   - Unable to find the configuration class fr.inria.atlanmod.neoemf.graph.blueprints.neo4j.config.BlueprintsNeo4jConfig
java.lang.ClassNotFoundException: fr.inria.atlanmod.neoemf.graph.blueprints.neo4j.config.BlueprintsNeo4jConfig cannot be found by fr.inria.atlanmod.neoemf.graph.blueprints_0.0.1.201510141510
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackendFactory.createPersistentBackend(BlueprintsPersistenceBackendFactory.java:114)
	at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackendFactory.createPersistentBackend(BlueprintsPersistenceBackendFactory.java:46)
	at fr.inria.atlanmod.neoemf.resources.impl.PersistentResourceImpl.save(PersistentResourceImpl.java:167)
	at org.lisa.air.server.infrastructure.internal.persistence.ModelPersistence.saveArchitectureDescription(ModelPersistence.java:109)
	at org.lisa.air.server.infrastructure.LisaAirServerInfrastructureActivator$3.execute(LisaAirServerInfrastructureActivator.java:430)
	at org.eclipse.emf.common.command.BasicCommandStack.execute(BasicCommandStack.java:78)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.basicExecute(AbstractTransactionalCommandStack.java:241)
	at org.eclipse.emf.transaction.impl.TransactionalCommandStackImpl.doExecute(TransactionalCommandStackImpl.java:63)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:219)
	at org.lisa.air.server.infrastructure.LisaAirServerInfrastructureActivator.saveArchitectureDescription(LisaAirServerInfrastructureActivator.java:396)
	at org.lisa.air.server.infrastructure.LisaAirServerInfrastructureActivator.access$5(LisaAirServerInfrastructureActivator.java:390)
	at org.lisa.air.server.infrastructure.LisaAirServerInfrastructureActivator$4.run(LisaAirServerInfrastructureActivator.java:499)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
fr.inria.atlanmod.neoemf.datastore.InvalidDataStoreException: java.lang.RuntimeException: GraphFactory could not find [com.tinkerpop.blueprints.impls.neo4j.Neo4jGraph].  Ensure that the jar is in the classpath.
	at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackendFactory.createPersistentBackend(BlueprintsPersistenceBackendFactory.java:159)
	at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackendFactory.createPersistentBackend(BlueprintsPersistenceBackendFactory.java:46)
	at fr.inria.atlanmod.neoemf.resources.impl.PersistentResourceImpl.save(PersistentResourceImpl.java:167)
	at org.lisa.air.server.infrastructure.internal.persistence.ModelPersistence.saveArchitectureDescription(ModelPersistence.java:109)
	at org.lisa.air.server.infrastructure.LisaAirServerInfrastructureActivator$3.execute(LisaAirServerInfrastructureActivator.java:430)
	at org.eclipse.emf.common.command.BasicCommandStack.execute(BasicCommandStack.java:78)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.basicExecute(AbstractTransactionalCommandStack.java:241)
	at org.eclipse.emf.transaction.impl.TransactionalCommandStackImpl.doExecute(TransactionalCommandStackImpl.java:63)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:219)
	at org.lisa.air.server.infrastructure.LisaAirServerInfrastructureActivator.saveArchitectureDescription(LisaAirServerInfrastructureActivator.java:396)
	at org.lisa.air.server.infrastructure.LisaAirServerInfrastructureActivator.access$5(LisaAirServerInfrastructureActivator.java:390)
	at org.lisa.air.server.infrastructure.LisaAirServerInfrastructureActivator$4.run(LisaAirServerInfrastructureActivator.java:499)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: GraphFactory could not find [com.tinkerpop.blueprints.impls.neo4j.Neo4jGraph].  Ensure that the jar is in the classpath.
	at com.tinkerpop.blueprints.GraphFactory.open(GraphFactory.java:34)
	at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackendFactory.createPersistentBackend(BlueprintsPersistenceBackendFactory.java:157)
	... 19 more

**Comment by gdaniel** [comment]
Did you add fr.inria.atlanmod.neoemf.graph.blueprints.neo4j in the require-bundle directive?

**Comment by buchgeher** [comment]
yes

**Comment by gdaniel** [comment]
Fixed, please update your installation with the new version of the update site.
(It was another OSGI error, there is still some tests to do on the OSGI bundles, thanks for the feedback)
