### ISSUE TITLE
Memory problems when converting a resource from XMI to Neo4j

### ISSUE THREAD

**Issue by philip-iii** [atlanmod/NeoEMF#66]
Out of Memory exceptions occur (despite 10GB memory allocation) when converting an XMI resource to a Neo4j resource. The XMI resource is still rather small (~250MB) so in theory it should work just fine, however, it results in OOM Exceptions:

`Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.Long.valueOf(Long.java:840)
        at org.neo4j.kernel.impl.cache.SoftLruCache.get(SoftLruCache.java:71)
        at org.neo4j.kernel.impl.core.NodeManager.getNodeByIdOrNull(NodeManager.java:307)
        at org.neo4j.kernel.impl.core.NodeManager.getNodeById(NodeManager.java:336)
        at org.neo4j.kernel.impl.core.NodeManager.nodeAddProperty(NodeManager.java:1081)
        at org.neo4j.kernel.impl.core.NodeImpl.addProperty(NodeImpl.java:129)
        at org.neo4j.kernel.impl.core.Primitive.setProperty(Primitive.java:436)
        at org.neo4j.kernel.impl.core.NodeImpl.setProperty(NodeImpl.java:53)
        at org.neo4j.kernel.impl.core.NodeProxy.setProperty(NodeProxy.java:130)
        at com.tinkerpop.blueprints.impls.neo4j.Neo4jElement.setProperty(Neo4jElement.java:42)
        at com.tinkerpop.blueprints.impls.neo4j.Neo4jVertex.setProperty(Neo4jVertex.java:20)
        at com.tinkerpop.blueprints.util.wrappers.id.IdElement.setProperty(IdElement.java:54)
        at com.tinkerpop.blueprints.util.wrappers.id.IdVertex.setProperty(IdVertex.java:47)
        at com.tinkerpop.blueprints.util.ElementHelper.copyProperties(ElementHelper.java:49)
        at com.tinkerpop.blueprints.util.GraphHelper.copyGraph(GraphHelper.java:63)
        at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackend.copyTo(BlueprintsPersistenceBackend.java:320)
        at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackendFactory.copyBackend(BlueprintsPersistenceBackendFactory.java:172)
        at fr.inria.atlanmod.neoemf.resource.DefaultPersistentResource.save(DefaultPersistentResource.java:145)`

or 

`Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.neo4j.kernel.impl.nioneo.store.LongerShortString.encode(LongerShortString.java:589)
        at org.neo4j.kernel.impl.nioneo.store.PropertyStore.encodeValue(PropertyStore.java:533)
        at org.neo4j.kernel.impl.nioneo.xa.WriteTransaction.nodeAddProperty(WriteTransaction.java:1240)
        at org.neo4j.kernel.impl.persistence.PersistenceManager.nodeAddProperty(PersistenceManager.java:144)
        at org.neo4j.kernel.impl.core.NodeManager.nodeAddProperty(NodeManager.java:1085)
        at org.neo4j.kernel.impl.core.NodeImpl.addProperty(NodeImpl.java:129)
        at org.neo4j.kernel.impl.core.Primitive.setProperty(Primitive.java:436)
        at org.neo4j.kernel.impl.core.NodeImpl.setProperty(NodeImpl.java:53)
        at org.neo4j.kernel.impl.core.NodeProxy.setProperty(NodeProxy.java:130)
        at com.tinkerpop.blueprints.impls.neo4j.Neo4jElement.setProperty(Neo4jElement.java:42)
        at com.tinkerpop.blueprints.impls.neo4j.Neo4jVertex.setProperty(Neo4jVertex.java:20)
        at com.tinkerpop.blueprints.util.wrappers.id.IdElement.setProperty(IdElement.java:54)
        at com.tinkerpop.blueprints.util.wrappers.id.IdVertex.setProperty(IdVertex.java:47)
        at com.tinkerpop.blueprints.util.ElementHelper.copyProperties(ElementHelper.java:49)
        at com.tinkerpop.blueprints.util.GraphHelper.copyGraph(GraphHelper.java:63)
        at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackend.copyTo(BlueprintsPersistenceBackend.java:320)
        at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackendFactory.copyBackend(BlueprintsPersistenceBackendFactory.java:172)
        at fr.inria.atlanmod.neoemf.resource.DefaultPersistentResource.save(DefaultPersistentResource.java:145)`

Both on the same resource after 8-10min of runtime. Smaller resources were converted without issue, but according to the benchmarks it should be possible to convert even bigger resources (target models are several GB in size). 

So far the standard API was used: load XMI resource, create Neo4j resource, add contents of XMI resource to Neo4j resource, save Neo4j resource.

Any hints on what kind of options or patterns shall be used to enable the conversion of larger models?

**Comment by gdaniel** [comment]
Hi Philip,

Thanks for reporting this issue, the stack trace you sent seems to show that you are using in-memory stores that you save at the end of the execution.
If I am right your code should look like
```java
Resource xmiResource = resourceSet.getResource(xmiURI)
Resource neoEMFResource = resourceSet.createResource(neoemfURI);
neoEMFResource.getContents().addAll(xmiResource.getContents())
neoEMFResource.save();
```
Using this approach is not efficient and may produce `OutOfMemoryErrors` because we have to keep everything in memory before the final save. When the save method is called the entire in-memory graph is copied to a Neo4j database (the `copyGraph` call in the stack trace), that can take a lot of time and consume a lot of memory.

If you want to save a large model with a limited memory consumption I suggest to use the same code as in the [demo](https://github.com/atlanmod/NeoEMF/blob/master/examples/fr.inria.atlanmod.neoemf.demo/src/fr/inria/atlanmod/neoemf/demo/importer/BlueprintsImporter.java):

```java
Resource persistentResource = rSet.createResource(
    BlueprintsURI.createFileURI(
        new File("models/sample.graphdb")
    )
)
Map<String, Object> options = BlueprintsNeo4jOptionsBuilder.newBuilder().
    weakCache()
    .autocommit()
    .asMap();
// save the resource before moving the objects to create the Neo4j database
persistentResource.save(options);
Resource xmiResource = rSet.createResource(URI.createURI("models/sample.xmi"));
xmiResource.load(Collections.emptyMap());

persistentResource.getContents().addAll(EcoreUtil.copyAll(xmiResource.getContents()));
// "regular" save
persistentResource.save(options);
```

The important point here is to first save the resource, even if it is empty. This allows NeoEMF to create a PersistentBackend (here Neo4j) instead of a TransientBackend (transient backends stay in memory unti a `save` method is called, and have to be entirely copied in the persistent backend).
We also set the `weakCache` and `autocommit` options. The first one limits the memory consumption of the Neo4j cache, and the second one automatically saves elements in the database every `n` instructions. The `autocommit` feature is important when you import a large model, because it limits the memory consumption a lot by flushing periodically the model elements in the database, making them eligible for garbage collection.

I hope this helps you. If this doesn't solve the problem please contact me again and I'll try to figure out what is going on.

I also just realized this "save before insert" feature is not in the wiki anymore, I'll put it back soon.

Regards,

Gwendal

**Comment by erdalkaraca** [comment]
Why is it neccessary to use EcoreUtil.copyAll()? Does not this mechanism use regular EMF API, i.e. loads the XMI resource into memory? Or will NeoEMF optimize this?

**Comment by gdaniel** [comment]
This code uses regular EMF API, even if you remove the `EcoreUtil.copyAll()` method. We put this method call in the example because we have found some consistency issues that occurs for unknown reasons (for now) when EObject are simply moved from one resource to another (see #62).

If you don't want to use the standard API to create a NeoEMF resource, because you cannot load the XMI file for example, you can use the efficient blueprints importer (see [here](https://github.com/atlanmod/NeoEMF/blob/master/examples/fr.inria.atlanmod.neoemf.demo/src/fr/inria/atlanmod/neoemf/demo/importer/EfficientBlueprintsImporter.java)) which consists of a dedicated XMI parser implementation that directly writes the model in a Blueprints database without using the standard EMF API. Note that this importer consumes way less memory than the standard solution.

For now we only provide an efficient importer for Blueprints, but support for other backends will come in the future.

**Comment by philip-iii** [comment]
Hi Gwendal,

thanks for the quick response and for the helpful hints! Indeed, using the approach you suggested, I was able to convert the ~250MB model successfully. I managed to find the solution in the examples in the meantime as well. I think, but updating the tutorial should help new users to get started on the right track much faster.

However, when I tried a 2GB model using the same approach, still ran into a memory problem. I may try the efficient blueprints importer next, but I ran into a different issue when using the Epsilon Object Language (EOL) for creating new objects.

Cheers,

Philip

**Comment by gdaniel** [comment]
Hi Philip,

You are right, we need to update the tutorial with these informations. @sunye could you have a look on it? I think we should also add the `EcoreUtil.copyAll` issue in the wiki for the moment: it is clearly not straightforward and can make newcomers think NeoEMF is not working.

Let me know if you need any help for the 2GB model, I ran some experiments recently with models of this size and everything worked quite well. If you have issues with EOL on top of NeoEMF I suggest to have a look on https://github.com/gdaniel/emc-neoemf. This repository contains an EMC driver for NeoEMF. I made it on my spare time and it's not up-to-date (I think it works with NeoEMF 1.0.0) but it can provide some help on EOL/NeoEMF integration.

Cheers,

Gwendal
