### ISSUE TITLE
Scalability issue with a big list in a model using NeoEMF, but not when using XMI

### ISSUE THREAD

**Issue by orichalque** [atlanmod/NeoEMF#76]
Hello,
In my current project I have a model using my own MetaModel generated using NeoEMF genmodel.
In order to compare the XMI persistence layer with NeoEMF, I'm increasing the size of this model until my VM crashes due to a lack of memory. VM options: `-Dosgi.requiredJavaVersion=1.6 -Xms40m -Xmx256m -server -XX:+UseConcMarkSweepGC`

In this model I have an element owning a list of references to other elements of the same model.
Programmatically, I add multiple element to this list, until it crashes. 

Using XMI I can get up to ~150 000 references in this list, without having a crash, but using NeoEMF my VM crashes way before reaching ~150k references, with the following stack traces: 

```Caused by: java.lang.OutOfMemoryError: Java heap space
Exception in thread "[Timer] - Main Queue Handler" java.lang.OutOfMemoryError: Java heap space
Exception in thread "GC-Monitor" java.lang.OutOfMemoryError: Java heap space
	at java.util.ResourceBundle$Control.getCandidateLocales(ResourceBundle.java:2367)
	at sun.util.resources.LocaleData$LocaleDataResourceBundleControl.getCandidateLocales(LocaleData.java:209)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1356)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:890)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:167)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.util.resources.LocaleData.getBundle(LocaleData.java:163)
	at sun.util.resources.LocaleData.getDateFormatData(LocaleData.java:127)
	at java.text.DateFormatSymbols.initializeData(DateFormatSymbols.java:710)
	at java.text.DateFormatSymbols.<init>(DateFormatSymbols.java:145)
	at sun.util.locale.provider.DateFormatSymbolsProviderImpl.getInstance(DateFormatSymbolsProviderImpl.java:85)
	at java.text.DateFormatSymbols.getProviderInstance(DateFormatSymbols.java:364)
	at java.text.DateFormatSymbols.getInstance(DateFormatSymbols.java:340)
	at java.util.Calendar.getDisplayName(Calendar.java:2110)
	at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1125)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:966)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
	at java.text.DateFormat.format(DateFormat.java:345)
	at org.neo4j.helpers.Format$ThreadLocalFormat.format(Format.java:132)
	at org.neo4j.helpers.Format.date(Format.java:56)
	at org.neo4j.helpers.Format.date(Format.java:36)
	at org.neo4j.helpers.Format.date(Format.java:31)
	at org.neo4j.kernel.impl.util.StringLogger$ActualStringLogger.time(StringLogger.java:519)
	at org.neo4j.kernel.impl.util.StringLogger$ActualStringLogger.logMessage(StringLogger.java:503)
	at org.neo4j.kernel.impl.cache.MeasureDoNothing.run(MeasureDoNothing.java:84)
```

```!ENTRY org.eclipse.core.jobs 4 2 2017-05-09 10:29:53.407
!MESSAGE Unhandled error
!STACK 0
java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap$KeySet.iterator(HashMap.java:916)
	at java.util.HashSet.iterator(HashSet.java:172)
	at org.eclipse.core.internal.jobs.JobManager.findBlockingJob(JobManager.java:736)
	at org.eclipse.core.internal.jobs.JobManager.nextJob(JobManager.java:1109)
	at org.eclipse.core.internal.jobs.JobManager.startJob(JobManager.java:1606)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:221)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:52)
```

I'm building the NeoEMF model from a XMI one, using NeoEMF's `Importer.fromXmi(xmiFile, neoEmfFile)`, this way:

```
PersistenceBackendFactoryRegistry.register(BlueprintsURI.SCHEME, BlueprintsPersistenceBackendFactory.getInstance());
this.resourceSet.getResourceFactoryRegistry().getProtocolToFactoryMap().put(BlueprintsURI.SCHEME, PersistentResourceFactory.getInstance());
Resource resource = this.resourceSet.createResource(BlueprintsURI.createFileURI(neoEmfFile));
resource.load(BlueprintsNeo4jOptionsBuilder.newBuilder().softCache().memoryMappedBuffers(true).asMap());
```

Do you know where this might come from ? Tell me if you need any more information about my code.

**Comment by gdaniel** [comment]
Closed, using autocommit in the option builder fixes the issue (see [AbstractBlueprintsOptionsBuilder#autocommit(int)](https://github.com/atlanmod/NeoEMF/blob/master/neoemf-data/blueprints/core/src/main/java/fr/inria/atlanmod/neoemf/data/blueprints/option/AbstractBlueprintsOptionsBuilder.java) for more information).
