### ISSUE TITLE
commons-io not included in plug-in files

### ISSUE THREAD

**Issue by timeraider4u** [atlanmod/NeoEMF#8]
When I calll `final URI uri = NeoBlueprintsURI.createNeoGraphURI(fileUri);`
I get the following exception:
`java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.getFile([Ljava/lang/String;)Ljava/io/File;
	at fr.inria.atlanmod.neoemf.graph.blueprints.util.NeoBlueprintsURI.createNeoGraphURI(NeoBlueprintsURI.java:31)`
Could you please add Apache commons-io.jar to the resulting jar file `fr.inria.atlanmod.neoemf.graph.blueprints_0.0.1.201510191301` and also enter it into the MANIFEST? Thanks a lot!

**Comment by timeraider4u** [comment]
Unfortunately I still get this error in the current development version:
`java.lang.NoSuchMethodError:`` org.apache.commons.io.FileUtils.getFile([Ljava/lang/String;)Ljava/io/File;
	at fr.inria.atlanmod.neoemf.graph.blueprints.util.NeoBlueprintsURI.createNeoGraphURI(NeoBlueprintsURI.java:31)
	at at.jku.weiner.c.modisco.discoverer.backend.NeoEMFSerializationBackend.createTargetURI(NeoEMFSerializationBackend.java:72)
	at at.jku.weiner.c.modisco.discoverer.backend.SerializationBackend.updateTargetURI(SerializationBackend.java:62)
	at at.jku.weiner.c.modisco.discoverer.actions.AbstractDiscovererWithLogic.initialize(AbstractDiscovererWithLogic.java:88)
	at at.jku.weiner.c.modisco.discoverer.actions.AbstractDiscovererWithLogic.discover2(AbstractDiscovererWithLogic.java:54)
	at at.jku.weiner.c.modisco.discoverer.actions.AbstractDiscovererWithLogic.discover(AbstractDiscovererWithLogic.java:39)
	at at.jku.weiner.c.modisco.discoverer.actions.impl.DiscoverFromIResource.basicDiscoverElement(DiscoverFromIResource.java:19)
	at at.jku.weiner.c.modisco.discoverer.actions.impl.DiscoverFromIResource.basicDiscoverElement(DiscoverFromIResource.java:1)
	at org.eclipse.modisco.infra.discovery.core.AbstractDiscoverer.discoverElement(AbstractDiscoverer.java:93)
	at org.eclipse.modisco.infra.discovery.core.AbstractModelDiscoverer.discoverElement(AbstractModelDiscoverer.java:183)
	at at.jku.weiner.c.modisco.discoverer.tests.TestUtils.<init>(TestUtils.java:55)
	at at.jku.weiner.c.modisco.discoverer.tests.EMFTest.emfTest(EMFTest.java:70)
	at at.jku.weiner.c.modisco.discoverer.tests.EMFTest.emfTest(EMFTest.java:52)
	at at.jku.weiner.c.modisco.discoverer.tests.emftests.Test0002_Empty.checkParserResult(Test0002_Empty.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
`

**Comment by timeraider4u** [comment]
fixed with latest commit [https://github.com/atlanmod/NeoEMF/pull/9#event-585256192](https://github.com/atlanmod/NeoEMF/pull/9#event-585256192)
