### ISSUE TITLE
Invalid characters in field names with Orient.db backend

### ISSUE THREAD

**Issue by graham2071** [atlanmod/NeoEMF#87]
Hello,

I've tried to use an Orient.db backend throught blueprints.
The created graph class is: "com.tinkerpop.blueprints.impls.orient.ORientGraph".
When adding elements to the model, the following errors occurs:
java.lang.IllegalArgumentException: Invalid field name 'ownedElement:size'. Character ':' is invalid
                at com.orientechnologies.orient.core.record.impl.ODocument.checkFieldName(ODocument.java:2647)
                at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:1060)
                at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:914)
                at com.tinkerpop.blueprints.impls.orient.OrientElement.setProperty(OrientElement.java:194)
                at com.tinkerpop.blueprints.util.wrappers.id.IdElement.setProperty(IdElement.java:54)
                at com.tinkerpop.blueprints.util.wrappers.id.IdVertex.setProperty(IdVertex.java:47)
                at fr.inria.atlanmod.neoemf.data.blueprints.store.DirectWriteBlueprintsStore.setSize(DirectWriteBlueprintsStore.java:524)
                at fr.inria.atlanmod.neoemf.data.blueprints.store.DirectWriteBlueprintsStore.clearReference(DirectWriteBlueprintsStore.java:463)
                at fr.inria.atlanmod.neoemf.data.store.AbstractDirectWriteStore.clear(AbstractDirectWriteStore.java:278)
                at fr.inria.atlanmod.neoemf.core.DefaultPersistentEObject.resource(DefaultPersistentEObject.java:163)
                at fr.inria.atlanmod.neoemf.resource.DefaultPersistentResource$ResourceContentsEStoreEList.delegateAdd(DefaultPersistentResource.java:454)
                at org.eclipse.emf.common.util.DelegatingEList.addAllUnique(DelegatingEList.java:402)
                at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.doAddAllUnique(DelegatingNotifyingListImpl.java:491)
                at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.addAllUnique(DelegatingNotifyingListImpl.java:464)
                at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.addAllUnique(DelegatingNotifyingListImpl.java:392)
                at org.eclipse.emf.common.util.AbstractEList.addAll(AbstractEList.java:372)

The version used is NeoEMF 1.0.2
orientdb-graphdb 2.2.31
JDK 8u144

Not sure if the problem comes from NeoEMF or Orient.db. Or me.
Is the field name generation configurable ?

(Note: Same test works fine with Neo4J backend).

**Comment by gdaniel** [comment]
Hello Graham,

This is a NeoEMF issue: we are using ':' as an internal sperator, and seems to conflict with OrientDB. Sadly we don't provide any way to configure the field name generation, but I'll think about a workaround and keep you posted.

Gwendal

**Comment by yvernageau** [comment]
Looking at the OrientDB schema validation method, I see that only `:`, `,` and space are forbidden.
We can simply replace the `:` character by an underscore, which is more common to delimit field names in databases. It's already used to prefix the `__id` property of vertices and edges in Blueprints, so I think it's a safe solution.

Concerned method: https://github.com/nengxu/OrientDB/blob/master/core/src/main/java/com/orientechnologies/orient/core/metadata/schema/OSchemaShared.java, line 280

**Comment by abelgomez** [comment]
One comment, @yvernageau 

The colon was chosen because it's and invalid character in EMF and Java identifiers as opposed to _, which can be part of EStructuralFeature names. That was done with the goal of ensuring that there won't be collisions and/or ambiguities between generated labels and the names of EStructuralFeatures.

Although collisions should not happen is the metamodel is properly queried, this is a useful feature when debugging how things are saved in the backend: E.g., if an underscore is used, it is not straightforward to distinguish between a single-valued EStructuralFeature called "feature_size" and the meta-property "size" of a many-valued EStructuralFeature calle "feature" (which will also be saved as "feature_size").

This also assumes that the `String.split()` function is not used in conjunction with the SEPARATOR String (which AFAIK is not the case).

I just wanted to mention this, just in case you may wish to consider other charaxcter that cannot be used in EMF identifiers but are valid as Blueprints identifiers.

Cheers!

**Comment by yvernageau** [comment]
Indeed, thanks to mention it. This method can't work on the `master` branch where features are still identified by their name, in the database.

However, on the `backend-abstraction` branch, which is waiting for the merge, features are identified by their EMF identifier, as an `Integer`, so it should not be a problem. The resulting field name should take this form: `0_size`.

I applied this modification, and features are correctly saved and recovered with Tinkergraph and Neo4j2. I will do some tests with OrientDB to make sure the problem is solved.

**Comment by abelgomez** [comment]
I imagined that in the `backend-abstraction` branch things worked in a different way, and indeed I was not sure that this was still valid for `master`. anyway, I just wanted to provide a rationale for this design decission :)
